global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 15s

scrape_configs:
#######################################################
### job: kernel_vm_node_kc_dataengineering
#######################################################
- job_name: kernel_vm_node_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.21.1.1:59100
    - 172.21.1.10:59100
    - 172.21.1.88:59100
    - 172.21.1.89:59100
    - 172.21.1.90:59100
    - 172.21.1.110:59100
    - 172.21.1.188:59100
    - 172.21.1.189:59100
    - 172.21.1.190:59100
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'

#######################################################
### job: kernel_vm_container_kc_dataengineering
#######################################################
- job_name: kernel_vm_container_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /proxy/monitoring/kc/cadvisor/metrics
  static_configs:
  - targets:
    - 172.21.1.1:59101
    - 172.21.1.10:59101
    - 172.21.1.88:59101
    - 172.21.1.89:59101
    - 172.21.1.90:59101
    - 172.21.1.110:59101
    - 172.21.1.188:59101
    - 172.21.1.189:59101
    - 172.21.1.190:59101
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'

#######################################################
### job: kernel_networking_nginx_master_kc_dataengineering
#######################################################
- job_name: kernel_networking_nginx_master_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /ops/monitoring/vts/format/prometheus
  static_configs:
  - targets:
    - 172.21.1.10:80
    - 172.21.1.88:80
    - 172.21.1.89:80
    - 172.21.1.90:80
    - 172.21.1.110:80
    - 172.21.1.188:80
    - 172.21.1.189:80
    - 172.21.1.190:80
  tls_config:
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'

#######################################################
### job: kernel_networking_nginx_outbound_kc_dataengineering
#######################################################
- job_name: kernel_networking_nginx_outbound_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /ops/monitoring/vts/format/prometheus
  static_configs:
  - targets:
    - 172.21.1.10:8080
    - 172.21.1.88:8080
    - 172.21.1.89:8080
    - 172.21.1.90:8080
    - 172.21.1.110:8080
    - 172.21.1.188:8080
    - 172.21.1.189:8080
    - 172.21.1.190:8080
  tls_config:
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'

#######################################################
### job: kernel_networking_openvpn_kc_dataengineering
#######################################################
- job_name: kernel_networking_openvpn_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.21.1.1:59176
    - 172.21.1.10:59176

#######################################################
### job: kernel_security_openldap_kc_dataengineering
#######################################################
- job_name: kernel_security_openldap_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.21.1.10:59330
    - 172.21.1.110:59330

# #######################################################
# ### job: devops_cicd_jenkins_kc_dataengineering
# #######################################################
- job_name: devops_cicd_jenkins_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /proxy/cicd/kc/jenkins/prometheus
  static_configs:
  - targets:
    - 172.21.1.10:58080
    - 172.21.1.110:58080

# #######################################################
# ### job: devops_cicd_nexus_kc_dataengineering
# #######################################################
- job_name: devops_cicd_nexus_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /proxy/cicd/kc/nexus/service/metrics/prometheus
  static_configs:
  - targets:
    - 172.21.1.10:58081
    - 172.21.1.110:58081

#######################################################
### job: data_kafka_kc_dataengineering
#######################################################
- job_name: data_kafka_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.21.1.188:59308
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'



#######################################################
### job: data_postgres_kc_dataengineering
#######################################################
- job_name: data_postgres_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.21.1.10:59187
    - 172.21.1.110:59187
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'

##############################################################
### job: data_spark_master_kc_dataengineering
##############################################################
- job_name: data_spark_master_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics/master/prometheus
  static_configs:
  - targets:
    - 172.21.1.188:57077
    labels:
      namespace: data_spark_kc_dataengineering
      cluster: prod_a
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'
  metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: org_apache_spark_$1

##############################################################
### job: data_spark_worker_kc_dataengineering
##############################################################
- job_name: data_spark_worker_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics/prometheus
  static_configs:
  - targets:
    - 172.21.1.188:58077
    - 172.21.1.189:58077
    - 172.21.1.190:58077
    labels:
      namespace: data_spark_kc_dataengineering
      cluster: prod_a
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'
  metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: org_apache_spark_$1

##############################################################
### job: data_spark_executors_kc_dataengineering
##############################################################
- job_name: data_spark_executors_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics/executors/prometheus
  static_configs:
  - targets:
    - 172.21.1.110:54077
    labels:
      namespace: data_spark_kc_dataengineering
      cluster: prod_a
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'
  metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: org_apache_spark_$1

##############################################################
### job: data_spark_streaming_kc_dataengineering
##############################################################
- job_name: data_spark_streaming_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics/prometheus
  static_configs:
  - targets:
    - 172.21.1.110:54077
    labels:
      namespace: data_spark_kc_dataengineering
      cluster: prod_a
      executor_id: driver
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: '^.*driver_spark_streaming.*'
    action: keep
  - source_labels: [__name__]
    target_label: application_id
    regex: '(metrics_)(.+?)_(.+?)_(.+)(_driver_spark_streaming_)(.+?)_(.+?)_(.+?)_(.+?)_(.+?)_(.*)'
    replacement: '${2}-${3}-${4}'
  - source_labels: [__name__]
    target_label: __name__
    regex: '(metrics_)(.+?)_(.+?)_(.+)(_driver_spark_streaming_)(.+?)_(.+?)_(.+?)_(.+?)_(.+?)_(.*)'
    replacement: org_apache_spark_metrics_sparkstreaming_${11}

##############################################################
### job: data_hadoop_kc_dataengineering
##############################################################
- job_name: data_hadoop_kc_dataengineering
  scrape_interval: 30s
  scrape_timeout:  25s
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.21.1.190:59020
    labels:
      cluster: hadoop-uat
      type: master
  - targets:
    - 172.21.1.188:59030
    - 172.21.1.189:59030
    - 172.21.1.190:59030
    labels:
      cluster: hadoop-uat
      type: agent
  # - targets:
  #   - 172.21.1.110:59020
  #   labels:
  #     cluster: hadoop-sandbox
  #     type: master
  # - targets:
  #   - 172.21.1.110:59030
  #   labels:
  #     cluster: hadoop-sandbox
  #     type: agent
  relabel_configs:
  - source_labels: [__address__]
    target_label: hostip_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${1}'
  - source_labels: [__address__]
    target_label: hostport_private
    regex: '([^:]+)(:[0-9]+)?'
    replacement: '${2}'
