[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "172.21.1.1"
# Default port is 389 or 636 if use_ssl = true
port = 1389
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = false
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = true
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"
# Search user bind dn
#bind_dn = 
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
#bind_password =
# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
# Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
search_filter = "(uid=%s)"
# An array of base dns to search through
search_base_dns = ["dc=danny,dc=com"]
group_search_filter = "(&(objectClass=groupOfNames)(member=uid=%s,ou=users,dc=danny,dc=com))"
group_search_filter_user_attribute = "uid"
group_search_base_dns = ["ou=groups,dc=danny,dc=com"]
# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "cn"
email =  "mail"

#Org 1 -> Kepler Cheuvreux
[[servers.group_mappings]]
group_dn = "role-admin"
org_role = "Admin"
org_id = 1
grafana_admin = true

[[servers.group_mappings]]
group_dn = "role-editor"
org_id = 1
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_id = 1
org_role = "Viewer"


#Org 2 -> Org 2
[[servers.group_mappings]]
group_dn = "role-admin"
org_role = "Admin"
org_id = 2
grafana_admin = true

[[servers.group_mappings]]
group_dn = "role-editor"
org_id = 2
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "role-viewer"
org_id = 2
org_role = "Viewer"

# Org 3 -> Org 3
[[servers.group_mappings]]
group_dn = "role-admin"
org_role = "Admin"
org_id = 3
grafana_admin = true

[[servers.group_mappings]]
group_dn = "role-editor"
org_id = 3
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "role-viewer"
org_id = 3
org_role = "Viewer"
