{
 "title": "2 - Service Tasks",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kcde_number_of_tasks_remaining, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kcde_number_of_tasks_remaining{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "executor_affinity",
    "label": "executor_affinity",
    "query": {
     "query": "label_values(kcde_task_target_latency_seconds{job=~\"$job\",instance=~\"$instance\"}, executor_affinity)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tasks - FixLogTracer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (seconds)  -  ULLINK > Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kcde_task_target_latency_seconds{instance=~'$instance', target=\"extract-rest-ullink-1\"}",
     "legendFormat": "{{executor_affinity}}"
    }
   ]
  },
  {
   "title": "Latency (seconds)  -  Service > Kafka",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kcde_task_target_latency_seconds{instance=~'$instance', target=\"load-kafka-1\"}",
     "legendFormat": "{{executor_affinity}}"
    }
   ]
  },
  {
   "title": "Rate - gRPC requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# tasks remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "kcde_number_of_tasks_remaining", "legendFormat": "__auto" }
   ]
  }
 ]
}