{
 "title": "Spark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{job=~\"data_spark_.*\"}, namespace)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(up{job=~\"data_spark_.*\"}, cluster)"
    }
   },
   {
    "name": "Application_name",
    "label": "Application_name",
    "query": {
     "query": "label_values(org_apache_spark_metrics_executor_rddBlocks{cluster=\"$Cluster\"}, application_name)"
    }
   },
   {
    "name": "Application_id",
    "label": "Application_id",
    "query": {
     "query": "label_values(org_apache_spark_metrics_executor_rddBlocks{cluster=\"$Cluster\", application_name=\"$Application_name\"}, application_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_master_workers_Value{namespace = \"$Namespace\",cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alive Workers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_master_aliveWorkers_Number{namespace=\"$Namespace\", cluster=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiting Apps",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_master_waitingApps_Value{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_master_apps_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_worker_executors_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Worker Memory Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_worker_memUsed_MB_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"} / (org_apache_spark_metrics_worker_memUsed_MB_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"} + org_apache_spark_metrics_worker_memFree_MB_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"} ) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_worker_coresUsed_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Used: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_worker_coresFree_Number{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Free: {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Spark Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Input Rate (messages/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_sparkstreaming_inputRate_total_Value{cluster=\"$Cluster\", application_id=\"$Application_id\"}",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Processing Rate (messages/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_sparkstreaming_processingRate_total_Value{cluster=\"$Cluster\", application_id=\"$Application_id\"}",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Last Observed Watermark (UTC)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_sparkstreaming_eventTime_watermark_Value{cluster=\"$Cluster\", application_id=\"$Application_id\"}",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_sparkstreaming_latency_Value{cluster=\"$Cluster\", application_id=\"$Application_id\"} / 1000",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "State Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_sparkstreaming_states_usedBytes_Value{cluster=\"$Cluster\", application_id=\"$Application_id\"} / 1000000",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Current State Rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_apache_spark_metrics_sparkstreaming_states_rowsTotal_Value{cluster=\"$Cluster\", application_id=\"$Application_id\"}",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Executors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (MB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_memoryUsed_bytes{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}/1000000",
       "legendFormat": "{{executor_id}}"
      },
      {}
     ]
    },
    {
     "title": "Disk Usage (MB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_diskUsed_bytes{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}/1000000",
       "legendFormat": "{{executor_id}}"
      },
      {}
     ]
    },
    {
     "title": "JVM Heap Memory (MB)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_JVMHeapMemory_bytes{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}/1000000",
       "legendFormat": "{{executor_id}}"
      },
      {}
     ]
    },
    {
     "title": "JVM Off Heap Memory (MB)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_JVMOffHeapMemory_bytes{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}/1000000",
       "legendFormat": "{{executor_id}}"
      },
      {}
     ]
    },
    {
     "title": "Failed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_failedTasks_total{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Completed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_completedTasks_total{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Active Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_activeTasks{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Rdd Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_rddBlocks{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Shuffle Bytes Read (kB/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "rate(org_apache_spark_metrics_executor_totalShuffleRead_bytes_total{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}[1m])/1000",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Shuffle Bytes Written(kB/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "targets": [
      {
       "expr": "rate(org_apache_spark_metrics_executor_totalShuffleWrite_bytes_total{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}[1m])/1000",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Executor GC Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "rate(org_apache_spark_metrics_executor_totalGCTime_seconds_total{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}[1m])",
       "legendFormat": "{{executor_id}}"
      }
     ]
    },
    {
     "title": "Total Duration (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_executor_totalDuration_seconds_total{namespace=\"$Namespace\",cluster=\"$Cluster\", application_name=\"$Application_name\", application_id=\"$Application_id\"}",
       "legendFormat": "{{executor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hive External Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_HiveExternalCatalog_fileCacheHits_Count{namespace=\"$Namespace\", cluster=\"$Cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Files Discovered",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 62 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_HiveExternalCatalog_filesDiscovered_Count{namespace=\"$Namespace\", cluster=\"$Cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Client Calls",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 62 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_HiveExternalCatalog_hiveClientCalls_Count{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Parallel Listing Job Count",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 4.8, "x": 14.4, "y": 62 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_HiveExternalCatalog_parallelListingJobCount_Count{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Partitions Fetched",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 62 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_HiveExternalCatalog_partitionsFetched_Count{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Code Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compilation Time",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_compilationTime_Max{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Max: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_compilationTime_Mean{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Mean: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_compilationTime_Min{namespace=\"$Namespace\"}",
       "legendFormat": "Min: {{instance}}"
      }
     ]
    },
    {
     "title": "Generated Method Size",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_generatedMethodSize_Max{namespace=\"$Namespace\"}",
       "legendFormat": "Max: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_generatedMethodSize_Mean{namespace=\"$Namespace\"}",
       "legendFormat": "Mean: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_generatedMethodSize_Min{namespace=\"$Namespace\"}",
       "legendFormat": "Min: {{instance}}"
      }
     ]
    },
    {
     "title": "Generated Class Size",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_generatedClassSize_Max{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Max: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_generatedClassSize_Mean{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Mean: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_generatedClassSize_Min{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Min: {{instance}}"
      }
     ]
    },
    {
     "title": "Source Code Size",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_sourceCodeSize_Max{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Max: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_sourceCodeSize_Mean{namespace=\"$Namespace\",cluster=\"$Cluster\"}",
       "legendFormat": "Mean: {{instance}}"
      },
      {
       "expr": "org_apache_spark_metrics_CodeGenerator_sourceCodeSize_Min{namespace=\"$Namespace\"}",
       "legendFormat": "Min: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}