{
 "title": "Spark > HDFS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Active_NameNode",
    "label": "Active_NameNode",
    "query": {
     "query": "label_values(up{job=\"data_hadoop_kc_dataengineering\", type=\"master\"}, instance)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"data_hadoop_kc_dataengineering\"}, cluster)"
    }
   },
   {
    "name": "datanode",
    "query": {
     "query": "label_values(up{job=\"data_hadoop_kc_dataengineering\", type=\"agent\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HDFS - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Live Datanodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(hadoop_NameNode_num_live_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "Live"
    }
   ]
  },
  {
   "title": "Number of datanode in each state",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(hadoop_NameNode_num_live_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "Live"
    },
    {
     "expr": "avg(hadoop_NameNode_num_decom_live_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "DecomLive"
    },
    {
     "expr": "avg(hadoop_NameNode_num_decommissioning_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "Decommissioning"
    },
    {
     "expr": "avg(hadoop_NameNode_num_in_maintenance_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(hadoop_NameNode_num_decom_dead_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "DecomDead"
    },
    {
     "expr": "avg(hadoop_NameNode_num_dead_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "Dead"
    },
    {
     "expr": "avg(hadoop_NameNode_num_stale_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "avg(hadoop_NameNode_num_in_service_live_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "InServiceLive"
    },
    {
     "expr": "avg(hadoop_NameNode_num_in_maintenance_live_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "InMaintenanceLive"
    },
    {
     "expr": "avg(hadoop_NameNode_num_in_maintenance_dead_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "InMaintenanceDead"
    },
    {
     "expr": "avg(hadoop_NameNode_num_entering_maintenance_data_nodes{cluster = \"$cluster\"})",
     "legendFormat": "EnteringMaintenance"
    }
   ]
  },
  {
   "title": "datanode_capacity",
   "type": "graph",
   "description": "Current raw capacity of DataNode in bytes",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_DataNode_capacity{cluster=\"$cluster\", instance=~\"$datanode\",fsdatasetid=~\".+\"}",
     "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
    }
   ]
  },
  {
   "title": "datanode_dfs_used",
   "type": "graph",
   "description": "Current space used by DataNodes for DFS purposes in bytes",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_DataNode_dfs_used{cluster=\"$cluster\", instance=~\"$datanode\", fsdatasetid=~\".+\"}",
     "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
    }
   ]
  },
  {
   "title": "datanode_remaining",
   "type": "graph",
   "description": "Current remaining capacity in bytes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_DataNode_remaining{cluster=\"$cluster\", instance=~\"$datanode\", fsdatasetid=~\".+\"}",
     "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
    }
   ]
  },
  {
   "title": "datanode_failed_volumes",
   "type": "graph",
   "description": "Total number of failed volumes",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_DataNode_num_failed_volumes{cluster=\"$cluster\", instance=~\"$datanode\",fsdatasetid=~\".+\"}",
     "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
    }
   ]
  },
  {
   "title": "HDFS - NameNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of datanode in each state",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(hadoop_NameNode_num_live_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "Live"
      },
      {
       "expr": "avg(hadoop_NameNode_num_decom_live_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "DecomLive"
      },
      {
       "expr": "avg(hadoop_NameNode_num_decommissioning_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "Decommissioning"
      },
      {
       "expr": "avg(hadoop_NameNode_num_in_maintenance_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(hadoop_NameNode_num_decom_dead_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "DecomDead"
      },
      {
       "expr": "avg(hadoop_NameNode_num_dead_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "Dead"
      },
      {
       "expr": "avg(hadoop_NameNode_num_stale_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "Stale"
      },
      {
       "expr": "avg(hadoop_NameNode_num_in_service_live_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "InServiceLive"
      },
      {
       "expr": "avg(hadoop_NameNode_num_in_maintenance_live_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "InMaintenanceLive"
      },
      {
       "expr": "avg(hadoop_NameNode_num_in_maintenance_dead_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "InMaintenanceDead"
      },
      {
       "expr": "avg(hadoop_NameNode_num_entering_maintenance_data_nodes{cluster = \"$cluster\"})",
       "legendFormat": "EnteringMaintenance"
      }
     ]
    },
    {
     "title": "fsname_system_num_active_clients",
     "type": "graph",
     "description": "\"NumActiveClients\": \"Current number of active clients holding lease\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_num_active_clients{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_num_files_under_construction",
     "type": "graph",
     "description": " \"NumFilesUnderConstruction\": \"Current number of files under construction\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_num_files_under_construction{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_total_load",
     "type": "graph",
     "description": " \"TotalLoad\": \"Current number of connections\",",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_total_load{cluster=\"$cluster\",kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_files_total",
     "type": "graph",
     "description": "\"FilesTotal\": \"Current number of files and directories\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_files_total{cluster=\"$cluster\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_blocks_total",
     "type": "graph",
     "description": "\"BlocksTotal\": \"Current number of allocated blocks in the system\",",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_blocks_total{cluster=\"$cluster\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "namenode_fsname_system_transactions_since_last_checkpoint",
     "type": "graph",
     "description": "Total number of transactions since last checkpoint",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_transactions_since_last_checkpoint{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "namenode_fsname_system_transactions_since_last_log_roll",
     "type": "graph",
     "description": "Total number of transactions since last edit log roll",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_transactions_since_last_log_roll{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_state_volume_failures_total",
     "type": "graph",
     "description": "\"VolumeFailuresTotal\": \"Total number of volume failures across all Datanodes\"",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_volume_failures_total{cluster=\"$cluster\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_pending_replication_blocks",
     "type": "graph",
     "description": "\"PendingReplicationBlocks\": \"Current number of blocks pending to be replicated\",",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_pending_replication_blocks{cluster=\"$cluster\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "namenode_nninfo_corrupt_file_count",
     "type": "graph",
     "description": "Corrupt file count",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_corrupt_files_count{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_corrupt_blocks",
     "type": "graph",
     "description": "\"CorruptBlocks\": \"Current number of blocks with corrupt replicas.\"",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_corrupt_blocks{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_stale_data_nodes",
     "type": "graph",
     "description": "\"StaleDataNodes\": \"Current number of DataNodes marked stale due to delayed heartbeat\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_stale_data_nodes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_missing_blocks",
     "type": "graph",
     "description": "\"MissingBlocks\": \"Current number of missing blocks\",",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_missing_blocks{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fsname_system_under_replicated_blocks",
     "type": "graph",
     "description": "\"UnderReplicatedBlocks\": \"Current number of blocks under replicated\",",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_under_replicated_blocks{kind=\"FSNamesystem\"}",
       "legendFormat": "{{cluster}} {{_target}}"
      }
     ]
    },
    {
     "title": "namenode_fsname_system_lock_queue_length",
     "type": "graph",
     "description": "Number of threads waiting to acquire FSNameSystem lock",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_lock_queue_length{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "namenode_fsname_system_expired_heartbeats",
     "type": "graph",
     "description": "Total number of expired heartbeats",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "hadoop_NameNode_expired_heartbeats{cluster=\"$cluster\"}",
       "legendFormat": " {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HDFS - DataNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "datanode_capacity",
     "type": "graph",
     "description": "Current raw capacity of DataNode in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_capacity{cluster=\"$cluster\", instance=~\"$datanode\",fsdatasetid=~\".+\"}",
       "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
      }
     ]
    },
    {
     "title": "datanode_dfs_used",
     "type": "graph",
     "description": "Current space used by DataNodes for DFS purposes in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_dfs_used{cluster=\"$cluster\", instance=~\"$datanode\", fsdatasetid=~\".+\"}",
       "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
      }
     ]
    },
    {
     "title": "datanode_remaining",
     "type": "graph",
     "description": "Current remaining capacity in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_remaining{cluster=\"$cluster\", instance=~\"$datanode\", fsdatasetid=~\".+\"}",
       "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
      }
     ]
    },
    {
     "title": "datanode_failed_volumes",
     "type": "graph",
     "description": "Total number of failed volumes",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_num_failed_volumes{cluster=\"$cluster\", instance=~\"$datanode\",fsdatasetid=~\".+\"}",
       "legendFormat": "{{instance}}-id-{{fsdatasetid}}"
      }
     ]
    },
    {
     "title": "datanode_bytes_written_rate",
     "type": "graph",
     "description": "Total rate of bytes written to DataNode",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_DataNode_bytes_written{cluster=\"$cluster\", instance=~\"$datanode\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_bytes_read_rate",
     "type": "graph",
     "description": "Total rate of bytes read from DataNode",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_DataNode_bytes_read{cluster=\"$cluster\", instance=~\"$datanode\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_total_write_time",
     "type": "graph",
     "description": "Total number of milliseconds spent on write operation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_total_write_time{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_total_read_time",
     "type": "graph",
     "description": "Total number of milliseconds spent on read operation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_total_read_time{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_fsync_count",
     "type": "graph",
     "description": "Total number of fsync",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_fsync_count{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "hadoop_hdfs_datanode_fsync_nanos_num_ops",
     "type": "graph",
     "description": "Total number of fsync",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_fsync_nanos_num_ops{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_send_data_packet_transfer_nanos_num_ops",
     "type": "graph",
     "description": "Total rate of sending packets",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_DataNode_send_data_packet_transfer_nanos_num_ops{cluster=\"$cluster\", instance=~\"$datanode\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_send_data_packet_transfer_nanos_avg_time",
     "type": "graph",
     "description": "Average transfer time of sending packets in nanoseconds",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_send_data_packet_transfer_nanos_avg_time{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_send_data_packet_blocked_on_network_nanos_num_ops",
     "type": "graph",
     "description": "Total rate of sending packets",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_DataNode_send_data_packet_blocked_on_network_nanos_num_ops{cluster=\"$cluster\", instance=~\"$datanode\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_send_data_packet_blocked_on_network_nanos_avg_time",
     "type": "graph",
     "description": "Average waiting time of sending packets in nanoseconds",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_send_data_packet_blocked_on_network_nanos_avg_time{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "hadoop_hdfs_datanode_fsync_nanos_avg_time",
     "type": "graph",
     "description": "Average fsync time in nanoseconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "hadoop_DataNode_fsync_nanos_avg_time{cluster=\"$cluster\", instance=~\"$datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_datanode_network_errors",
     "type": "graph",
     "description": "Total rate of datanode network error",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_DataNode_datanode_network_errors{cluster=\"$cluster\", instance=~\"$datanode\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}